### ISSUE TITLE
environment install

### ISSUE THREAD

**Issue by PhilipDW183** [mateoneira/urban_simulation#1]
For environment install I used the anaconda command prompt on windows 

I had to use: 
```

conda env create -f environment.yml 

conda activate urbsim

```

As the current environment install didn't work so I followed this: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html

Then use the python -m ipykernel install --user --name -urbsim --display-name "urbsim"

but I have the environment installed after this and can create a new notebook using this kernel going forward

**Comment by mateoneira** [comment]
Thanks for pointing that out, hadn't realised that the name of the environment was already in the .yml file. will update the README.
